### ISSUE TITLE
Consider refactoring use of HttpClient

### ISSUE THREAD

**Issue by mrstebo** [asukhodko/dotnet-logstash-http#1]
Offering a little advise about the use of the *supposedly* disposable `HttpClient`. I see you are creating a `HttpClient` [here](https://github.com/asukhodko/serilog-sinks-logstash-http/blob/master/Serilog.Sinks.LogstashHttp/Sinks/LogstashHttp/LogstashHttpSink.cs#L62), which looks **good and proper**. But I recently came across [this article](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) that explains that `HttpClient` is not a true disposable!

It would probably be a better idea to create a `static` instance of the `HttpClient` in the `LogstashHttpSink` class.

**Comment by asukhodko** [comment]
Made HttpClient singleton.
